"""empty message

Revision ID: 533098620a8e
Revises: b536b1622c91
Create Date: 2020-02-28 12:15:21.598659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533098620a8e'
down_revision = 'b536b1622c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Availability', sa.Column('end_time', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Availability', sa.Column('start_time', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Availability', 'times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Availability', sa.Column('times', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Availability', 'start_time')
    op.drop_column('Availability', 'end_time')
    # ### end Alembic commands ###
