"""empty message

Revision ID: 64ff541b248d
Revises: f0a63d44b726
Create Date: 2020-02-26 11:06:41.920337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ff541b248d'
down_revision = 'f0a63d44b726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('availability', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'availability')
    # ### end Alembic commands ###
